# æ˜¯å¦æ¿€æ´»å¤åˆ¶æ–‡ç« æ—¶è¿½åŠ åšå®¢å’Œä½œè€…çš„ç‰ˆæƒä¿¡æ¯.
copyright:
  enable: false # ä»£ç å—æ˜¯å¦å¯å¤åˆ¶,trueå…è®¸,falseåŠ ä¸Šæ–‡ç« ä¿¡æ¯
  minCharNumber: 80 # è‡³å°‘å¤åˆ¶å¤šå°‘ä¸ªå­—ç¬¦å°±è¿½åŠ ç‰ˆæƒä¿¡æ¯.
  description: æœ¬æ–‡ç« è‘—ä½œæƒå½’ä½œè€…æ‰€æœ‰ï¼Œä»»ä½•å½¢å¼çš„è½¬è½½éƒ½è¯·æ³¨æ˜å‡ºå¤„ã€‚

# site name
prefixName: ğŸ¼
siteName: Rookie_l's Blog
# favicon and site master avatar
favicon: https://icu007.work/wp-content/uploads/2022/08/cropped-cropped-icno.png
avatar: /img/custom/avatar.jpg
url: https://hiheya.github.io/
description: ä¸å›å…±èµ´ï¼Œä¸‡é‡Œå¾ç¨‹ã€‚
# cdn: https://cdn.jsdelivr.net/gh/hiheya/cdn@1.2
pjax: 1
# 1å¼€å¯
mathjax: 0

notice: æœ¬åšå®¢ä¸ºäº†ç¾è§‚ï¼Œæ–‡ç« å¤´å›¾å‡ä¸æ­£æ–‡æ— å…³ã€‚
lazyloadImg: https://cdn.jsdelivr.net/gh/hiheya/cdn@1.2/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  é¦–é¡µ: { path: /, fa: fa-fort-awesome faa-shake }
  å½’æ¡£: { path: /archives, fa: fa-archive faa-wrench, submenus: { 
    æŠ€æœ¯: {path: /categories/æŠ€æœ¯/, fa: fa-code }, 
    ç”Ÿæ´»: {path: /categories/ç”Ÿæ´»/, fa: fa-file-text-o }, 
    èµ„æº: {path: /categories/èµ„æº/, fa: fa-cloud-download }, 
    éšæƒ³: {path: /categories/éšæƒ³/, fa: fa-commenting-o }
  } }
  æ¸…å•: { path: javascript:;, fa: fa-list-ul faa-float, submenus: { 
    ä¹¦å•: {path: /tags/æ‚¦è¯»/, fa: fa-th-list faa-bounce }, 
    ç•ªç»„: {path: /bangumi/, fa: fa-film faa-passing }, 
    æ­Œå•: {path: /music/, fa: fa-headphones }
  } }
  æ ‡ç­¾: { path: /tags/, fa: fa fa-bookmark faa-ring, submenus: { 
    Java: {path: /tags/Java/, fa: fa-code faa-burst }, 
    éšç¬”: {path: /tags/éšç¬”/, fa: fa-file-text-o faa-falling }, 
    WP: {path: /tags/WordPress/, fa: fa fa-file-o faa-rising },
    ç¡¬ä»¶: {path: /tags/ç¡¬ä»¶/, fa: fa fa-bicycle faa-ring }
  } }
  åˆ†ç±»: { path: /category/, fa: fa fa-th-large faa-horizontal }
  ç•™è¨€: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  å‹é“¾: { path: /links/, fa: fa-link faa-vertical }
  èµèµ: { path: /donate/, fa: fa-heart faa-flash }
  å…³äº: { path: /about/, fa: fa-leaf faa-pulse }
  
  # RSS: { path: /atom.xml, fa: fa-rss faa-pulse }

post_description:
  - enable: true
# Home page sort type: -1: newer firstï¼Œ1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# èƒŒæ™¯å›¾ç‰‡ æ›´å¥½çš„ä¿®æ”¹
bg:
  - /img/background/img1.png
  - /img/background/img2.png
  - /img/background/img4.png
  - /img/background/img5.png
  - /img/background/img6.png
  - /img/background/img7.png
  - /img/background/img8.png
  # - https://api.ixiaowai.cn/mcapi/mcapi.php
  # - https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(1).jpg.webp
  #- https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(2).jpg.webp
  #- https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(3).jpg.webp
  #- https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(4).jpg.webp
  #- https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(5).jpg.webp
  #- https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(6).jpg.webp
  #- https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(7).jpg.webp
  #- https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(8).jpg.webp

# èƒŒæ™¯å›¾ç‰‡æ ·å¼ ç©º åŸå›¾æ•ˆæœ filter-dim é˜´å½± filter-grid æ¨ªæ¡ filter-dot ç‚¹ç‚¹
bgclass: 

# startdash url, title, desc img
startdash: 
  - {url: https://icu007.work, title: æˆ‘çš„ä¸»ç«™, desc: ç‚¹å‡»è®¿é—®ä¸»ç«™, img: /img/startdash/sakura.md.png}
  - {url: https://space.bilibili.com/55406380, title: Bilibili, desc: åšä¸»çš„bç«™è§†é¢‘, img: /img/startdash/bilibili.jpg}
  - {url: https://baidu.icu007.work, title: è®©æˆ‘å¸®ä½ ç™¾åº¦ä¸€ä¸‹, desc: æŠ€æœ¯æœåŠ¡, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 07/17/2022

#social  url, img PCç«¯é…ç½®
social:
  github: {url: http://github.com/hiheya, img: /img/social/github.png}
  sina: {url: https://weibo.com/u/5400016811, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=1300961291, img: /img/social/wangyiyun.png}
  zhihu: {url: https://www.zhihu.com/people/liao-xi-he, img: /img/social/zhihu.png}
  email: {url: mailto:rookie_l@icu007.work, img: /img/social/email.svg}
  wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  # wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img ç§»åŠ¨ç«¯é…ç½®
msocial:
  github: {url: http://github.com/hiheya, fa: fa-github, color: 333}
  weibo: {url: https://weibo.com/u/5400016811, fa: fa-weibo, color: dd4b39}
  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  # paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# è§†é¢‘åœ°å€ä¸ºhttps://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4ï¼Œé…ç½®å¦‚ä¸‹
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # å¤šä¸ªè§†é¢‘ç”¨é€—å·éš”å¼€ï¼Œéšæœºè·å–ã€‚æ”¯æŒçš„æ ¼å¼ç›®å‰å·²çŸ¥MP4,Flvã€‚å…¶ä»–çš„å¯ä»¥è¯•ä¸‹ï¼Œä¸ä¿è¯æœ‰ç”¨
  name: Unbroken.mp4

aplayer: 
  id: 6842714056
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: false
v_appId: GyC3NzMvd0hT9Yyd2hYIC0MN-gzGzoHsz
v_appKey: mgOpfzbkHYqU92CV4IDlAUHQ

# livere
livere: true
data_uid: MTAyMC81NzEzMi8zMzU5Ng==

# Waline
waline:
  enable: false
  serverURL: #æœåŠ¡ç«¯åœ°å€
  visitor: false #ç»Ÿè®¡é˜…è¯»é‡
  comment_count: true #ç»Ÿè®¡è¯„è®ºæ•°
  avatar: mp # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  placeholder: ç¥å¼€å¼€å¿ƒå¿ƒï¼ # Comment Box placeholder
  requiredFields: [ 'nick','mail' ] #è®¾ç½®å¿…å¡«é¡¹
  background: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich2.gif #è¾“å…¥æ¡†æç¤ºåŠ¨ç”»

  # æ˜¯å¦å¼€å¯å­—æ•°ç»Ÿè®¡
	#ä¸éœ€è¦ä½¿ç”¨ï¼Œç›´æ¥è®¾ç½®å€¼ä¸ºfalseï¼Œæˆ–æ³¨é‡Šæ‰
	word_count: true
